# Generated by Django 5.1.7 on 2025-04-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="Anonymous", max_length=255),
        ),
    ]
