version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: tsingleap_backend
      POSTGRES_PASSWORD: tsingleap_backend_password
      POSTGRES_DB: tsingleap_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
