"""
Django settings for tsingleap_backend project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import dotenv
dotenv.load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-)!iuu&8vhw(3h$=8g6i=n*^yvo1t!&3%)^erh3v2(125787yh#"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://tsingleap-frontend-tsingleap.app.spring25a.secoder.net",
    "https://tsingleap-frontend.tsingleap.secoder.local",
    "https://localhost:5173",
    "https://local.app.spring25a.secoder.net:5173"
]

CSRF_TRUSTED_ORIGINS = [
    "https://tsingleap-frontend-tsingleap.app.spring25a.secoder.net",
    "https://tsingleap-frontend.tsingleap.secoder.local",
    "https://localhost:5173",
    "https://local.app.spring25a.secoder.net:5173"
]
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_DOMAIN = '.app.spring25a.secoder.net'

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "tsingleap-backend.tsingleap.secoder.local",
    "tsingleap-backend-tsingleap.app.spring25a.secoder.net",
    "localhost:5173"
    "local.app.spring25a.secoder.net:5173"
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users",
    "settings",
    "competitions",
    "forum",
    "corsheaders",
    "tag",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tsingleap_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tsingleap_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# 使用 PostgreSQL 数据库
import os

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'tsingleap_db'),  # 你的数据库名称
        'USER': os.getenv('POSTGRES_USER', 'tsingleap_backend'),  # 你的数据库用户名
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'tsingleap_backend_password'),  # 你的数据库密码
        'HOST': os.getenv('POSTGRES_HOST', '127.0.0.1'),  # PostgreSQL 的服务器地址
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.qq.com"  # 你的邮件服务器，比如 Gmail, QQ 邮箱等
EMAIL_PORT = 465  # 465 (SSL) 或 587 (TLS)
EMAIL_USE_SSL = True  # 这里一般用 TLS，QQ 邮箱需要 SSL（`EMAIL_USE_SSL = True`）
EMAIL_HOST_USER = "tsingleap-auth@foxmail.com"  # 你的邮箱
EMAIL_HOST_PASSWORD = os.getenv('TSINGLEAP_EMAIL_HOST_PASSWORD', "ERROR!")  # 你的邮箱授权码（不能用真实密码！）
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # 发送者邮箱