# Generated by Django 5.1.7 on 2025-04-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="liked_num",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="liked_num",
            field=models.IntegerField(default=0),
        ),
    ]
