# Generated by Django 5.1.7 on 2025-04-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_comment_liked_num_post_liked_num"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="id",
            new_name="comment_id",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="id",
            new_name="post_id",
        ),
    ]
