# Generated by Django 5.1.7 on 2025-04-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_rename_id_comment_comment_id_rename_id_post_post_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="liked_num",
        ),
        migrations.RemoveField(
            model_name="post",
            name="liked_num",
        ),
    ]
