# Generated by Django 5.1.7 on 2025-04-24 17:14

from django.db import migrations

def migrate_post_comments(apps, schema_editor):
    Comment = apps.get_model('forum', 'Comment')
    Post = apps.get_model('forum', 'Post')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    ct = ContentType.objects.get_for_model(Post)
    for c in Comment.objects.all():
        if hasattr(c, 'post'):
            c.content_type = ct
            c.object_id = c.post.post_id
            c.save()

class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0007_comment_content_type_comment_object_id"),
    ]

    operations = [
        migrations.RunPython(migrate_post_comments),
    ]
