# Generated by Django 5.1.7 on 2025-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0011_alter_comment_content_type_alter_comment_object_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="allow_reply",
            field=models.BooleanField(default=True),
        ),
    ]
