# Generated by Django 5.1.7 on 2025-05-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0012_comment_allow_reply"),
        ("tag", "0004_remove_tag_competitions_remove_tag_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="tag.tag"
            ),
        ),
    ]
