# Generated by Django 5.1.7 on 2025-05-23 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0014_report"),
        ("users", "0003_alter_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="reported_content",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="reported_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_received",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_made",
                to="users.user",
            ),
        ),
    ]
