# Generated by Django 5.1.7 on 2025-05-23 16:57

from django.db import migrations
from forum.models import Report

def migrate_report_data(apps, schema_editor):
    for report in Report.objects.all():
        content_type_class = report.content_type.model_class()
        try:
            content_object = content_type_class.objects.get(pk=report.object_id)
            report.reported_user = content_object.author
            report.reported_content = content_object.content
        except content_type_class.DoesNotExist:
            report.reported_user = report.reporter
            report.reported_content = "error"
        report.save()

def reverse_migrate_report_data(apps, schema_editor):
    # 由于这是一个数据填充操作，反向迁移不需要做任何事情
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0015_report_reported_content_report_reported_user_and_more'),  # 请确保这里的依赖是正确的
    ]

    operations = [
        migrations.RunPython(migrate_report_data, reverse_migrate_report_data),
    ]
