# Generated by Django 5.1.7 on 2025-05-23 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0016_migrate_report_data"),
        ("users", "0003_alter_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reported_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="reported_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_received",
                to="users.user",
            ),
        ),
    ]
