# Generated by Django 5.1.7 on 2025-05-23 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0017_alter_report_reported_content_and_more"),
        ("users", "0003_alter_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reported_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_received1",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_made1",
                to="users.user",
            ),
        ),
    ]
