# Generated by Django 5.1.7 on 2025-05-23 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("forum", "0018_alter_report_reported_user_alter_report_reporter"),
        ("users", "0003_alter_user_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report2",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("reported_content", models.TextField()),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("solved", models.BooleanField(default=False)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to="users.user",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
