# Generated by Django 5.1.7 on 2025-05-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0019_report2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Report",
        ),
    ]
