# Generated by Django 5.1.7 on 2025-05-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("forum", "0020_delete_report"),
        ("users", "0003_alter_user_nickname"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Report2",
            new_name="Report",
        ),
    ]
