# Generated by Django 5.1.7 on 2025-05-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competitions", "0022_alter_competition_time_begin"),
        ("forum", "0012_comment_allow_reply"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=32)),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("user_liked", "用户点赞"),
                            ("user_follow", "用户关注"),
                            ("sports", "运动"),
                            ("department", "院系"),
                            ("featured", "精华帖"),
                            ("default", "默认"),
                        ],
                        default="default",
                        max_length=32,
                    ),
                ),
                ("is_post_tag", models.BooleanField()),
                ("is_competition_tag", models.BooleanField()),
                (
                    "competitions",
                    models.ManyToManyField(
                        related_name="tag", to="competitions.competition"
                    ),
                ),
                ("posts", models.ManyToManyField(related_name="tag", to="forum.post")),
            ],
        ),
    ]
