# Generated by Django 5.1.7 on 2025-05-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0022_alter_competition_time_begin"),
        ("forum", "0012_comment_allow_reply"),
        ("tag", "0002_alter_tag_tag_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="competitions",
            field=models.ManyToManyField(
                blank=True, related_name="tag", to="competitions.competition"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="posts",
            field=models.ManyToManyField(
                blank=True, related_name="tag", to="forum.post"
            ),
        ),
    ]
