# Generated by Django 5.1.7 on 2025-05-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0003_alter_tag_competitions_alter_tag_posts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="competitions",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="posts",
        ),
    ]
