# Generated by Django 5.1.7 on 2025-05-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0004_remove_tag_competitions_remove_tag_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag_type",
            field=models.CharField(
                choices=[
                    ("user_liked", "用户点赞"),
                    ("user_follow", "用户关注"),
                    ("sports", "运动"),
                    ("department", "院系"),
                    ("event", "赛事"),
                    ("highlight", "精华帖"),
                    ("default", "默认"),
                ],
                default="default",
                max_length=32,
            ),
        ),
    ]
