# Generated by Django 5.1.7 on 2025-04-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpermission",
            name="permission_info",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
