# Generated by Django 5.1.7 on 2025-04-19 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("sport", models.CharField(max_length=255)),
                ("competitor_a", models.CharField(max_length=255)),
                ("competitor_b", models.CharField(max_length=255)),
                ("score_a", models.IntegerField(default=0)),
                ("score_b", models.IntegerField(default=0)),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "time_begin",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 4, 19, 23, 38, 0, 542388)
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
