# Generated by Django 5.1.7 on 2025-04-20 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="time_begin",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 20, 2, 25, 10, 945816)
            ),
        ),
    ]
