# Generated by Django 5.1.7 on 2025-04-20 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0005_alter_competition_time_begin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="time_begin",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 20, 16, 9, 35, 682265)
            ),
        ),
    ]
