# Generated by Django 5.1.7 on 2025-04-26 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0019_alter_competition_time_begin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="time_begin",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 26, 15, 7, 14, 113084)
            ),
        ),
    ]
