# Generated by Django 5.1.7 on 2025-04-26 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0021_alter_competition_time_begin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="time_begin",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
