# Generated by Django 5.1.7 on 2025-05-11 16:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0021_alter_competition_time_begin"),
        ("users", "0003_alter_user_nickname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="competitor_a",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="competitor_b",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="score_a",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="score_b",
        ),
        migrations.AddField(
            model_name="competition",
            name="participants",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="competition",
            name="time_begin",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="Focus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.competition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
