# Generated by Django 5.1.7 on 2025-05-12 00:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0022_alter_competition_time_begin"),
        ("competitions", "0022_remove_competition_competitor_a_and_more"),
    ]

    operations = []
