# Generated by Django 5.1.7 on 2025-05-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0023_merge_20250512_0029"),
        ("tag", "0004_remove_tag_competitions_remove_tag_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="competition", to="tag.tag"
            ),
        ),
    ]
